### ISSUE TITLE
Unable to run wssh on CentOS 7

### ISSUE THREAD

**Issue by aaronnewsome** [huashengdun/webssh#133]
First, I want to express thank you for such an awesome bit of software.

I've got wssh running nicely on an Ubuntu system. Just followed the directions on the github page and it worked just fine.

Now I'm trying to get it up and running on a CentOS 7.7.1908 system and not having much luck.

First, when I try pip install wssh, I get a few messages about missing dependencies and other issues. The first error I fixed with "pip install --upgrade setuptools". Then I get an error message about enum. I fixed that with "pip install enum".

After fixing the missing modules, I try to run wssh, I get the following

`Traceback (most recent call last):
  File "/usr/bin/wssh", line 9, in <module>
    load_entry_point('webssh==1.5.1', 'console_scripts', 'wssh')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/webssh/main.py", line 6, in <module>
    from webssh import handler
  File "/usr/lib/python2.7/site-packages/webssh/handler.py", line 8, in <module>
    import paramiko
  File "/usr/lib/python2.7/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 129, in <module>
    class Transport(threading.Thread, ClosingContextManager):
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 190, in Transport
    if KexCurve25519.is_available():
  File "/usr/lib/python2.7/site-packages/paramiko/kex_curve25519.py", line 30, in is_available
    X25519PrivateKey.generate()
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/primitives/asymmetric/x25519.py", line 38, in generate
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 16, in <module>
    from cryptography import utils, x509
  File "/usr/lib64/python2.7/site-packages/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "/usr/lib64/python2.7/site-packages/cryptography/x509/base.py", line 18, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/usr/lib64/python2.7/site-packages/cryptography/x509/extensions.py", line 26, in <module>
    from cryptography.x509.general_name import GeneralName, IPAddress, OtherName
  File "/usr/lib64/python2.7/site-packages/cryptography/x509/general_name.py", line 16, in <module>
    from cryptography.x509.name import Name
  File "/usr/lib64/python2.7/site-packages/cryptography/x509/name.py", line 28, in <module>
    _ASN1_TYPE_TO_ENUM = dict((i.value, i) for i in _ASN1Type)
TypeError: 'type' object is not iterable
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 120, in _join_lingering_threads
    for thr in _active_threads:
TypeError: 'NoneType' object is not iterable
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 120, in _join_lingering_threads
    for thr in _active_threads:
TypeError: 'NoneType' object is not iterable`

Does anyone have any idea who to fix this? I'd really like to get it running on CentOS 7.

**Comment by sbwml** [comment]
I successfully run with python3 on centos7.7.1908

**Comment by sbwml** [comment]
root     15921 15830  0 02:10 pts/2    00:00:46 /usr/bin/python3 /usr/local/bin/wssh

https://ssh.cooluc.com/
