### ISSUE TITLE
cann't use webssh on centos7

### ISSUE THREAD

**Issue by wayneshow** [huashengdun/webssh#140]
raise erro :
```
[I 200319 16:03:39 transport:1819] Authentication (password) successful!
[E 200319 16:03:39 transport:1819] Secsh channel 1 open FAILED: open failed: Administratively prohibited
[E 200319 16:03:39 handler:507] Traceback (most recent call last):
      File "/usr/local/env3/lib/python3.6/site-packages/webssh/handler.py", line 505, in post
        worker = yield future
      File "/usr/local/env3/lib/python3.6/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/usr/local/python3/lib/python3.6/concurrent/futures/_base.py", line 425, in result
        return self.__get_result()
      File "/usr/local/python3/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
        raise self._exception
      File "/usr/local/python3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/local/env3/lib/python3.6/site-packages/webssh/handler.py", line 461, in ssh_connect
        self.get_default_encoding(ssh)
      File "/usr/local/env3/lib/python3.6/site-packages/webssh/handler.py", line 430, in get_default_encoding
        _, stdout, _ = ssh.exec_command(command, get_pty=True)
      File "/usr/local/env3/lib/python3.6/site-packages/paramiko/client.py", line 508, in exec_command
        chan = self._transport.open_session(timeout=timeout)
      File "/usr/local/env3/lib/python3.6/site-packages/paramiko/transport.py", line 879, in open_session
        timeout=timeout,
      File "/usr/local/env3/lib/python3.6/site-packages/paramiko/transport.py", line 1017, in open_channel
        raise e
    paramiko.ssh_exception.ChannelException: ChannelException(1, 'Administratively prohibited')
```
How solve this problem？

**Comment by huashengdun** [comment]
Try restarting the server like following:
```bash
wssh --encoding='utf-8'
```

**Comment by wayneshow** [comment]
@huashengdun 3Q！It works！
