### ISSUE TITLE
Closing worker 1657528138056 with reason: chan closed

### ISSUE THREAD

**Issue by lb20150514** [huashengdun/webssh#145]
[I 200408 14:06:25 handler:447] Connecting to arden-pv-003-drop8:22
[I 200408 14:06:25 transport:1819] Connected (version 2.0, client OpenSSH_7.6p1)
[I 200408 14:06:25 handler:87] Trying password authentication
[I 200408 14:06:25 transport:1819] Authentication (password) successful!
[I 200408 14:06:26 web:2250] 200 POST / (::1) 1522.38ms
[I 200408 14:06:27 web:2250] 101 GET /ws?id=1657528138056 (::1) 2.00ms
[I 200408 14:06:27 handler:533] Connected from ::1:53308
[I 200408 14:06:27 worker:115] Closing worker 1657528138056 with reason: chan closed
[I 200408 14:06:27 worker:122] Connection to arden-pv-003-drop8:22 lost
[I 200408 14:06:27 handler:579] Disconnected from ::1:53308

can you help you figure out what happen for channel closed problem? is this due to computer config or remote device config or others? thanks!

**Comment by huashengdun** [comment]
From the log I can see that the ssh server closes the connection at first.
You can run it in debug mode to show more logs.

**Comment by lb20150514** [comment]
wssh --logging=debug --debug
[D 200413 17:19:16 selector_events:53] Using selector: SelectSelector
[D 200413 17:19:16 policy:29] {'autoaddpolicy': <class 'webssh.policy.AutoAddPolicy'>, 'rejectpolicy': <class 'paramiko.client.RejectPolicy'>, 'warningpolicy': <class 'paramiko.client.WarningPolicy'>}
[I 200413 17:19:16 settings:125] WarningPolicy
Traceback (most recent call last):
  File "C:\Users\bo1li102\AppData\Local\Programs\Python\Python37\Scripts\wssh-script.py", line 11, in <module>
    load_entry_point('webssh==1.5.2', 'console_scripts', 'wssh')()
  File "C:\Users\bo1li102\AppData\Local\Programs\Python\Python37\lib\site-packages\webssh-1.5.2-py3.7.egg\webssh\main.py", line 50, in main
    app_listen(app, options.port, options.address, server_settings)
  File "C:\Users\bo1li102\AppData\Local\Programs\Python\Python37\lib\site-packages\webssh-1.5.2-py3.7.egg\webssh\main.py", line 32, in app_listen
    app.listen(port, address, **server_settings)
  File "C:\Users\bo1li102\AppData\Local\Programs\Python\Python37\lib\site-packages\tornado\web.py", line 2116, in listen
    server.listen(port, address)
  File "C:\Users\bo1li102\AppData\Local\Programs\Python\Python37\lib\site-packages\tornado\tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "C:\Users\bo1li102\AppData\Local\Programs\Python\Python37\lib\site-packages\tornado\netutil.py", line 174, in bind_sockets
    sock.bind(sockaddr)
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted


I'm in Windows environment, does it matters?

**Comment by lb20150514** [comment]
wssh --logging=debug --debug
[D 200414 10:48:10 selector_events:53] Using selector: SelectSelector
[D 200414 10:48:10 policy:29] {'autoaddpolicy': <class 'webssh.policy.AutoAddPolicy'>, 'rejectpolicy': <class 'paramiko.client.RejectPolicy'>, 'warningpolicy': <class 'paramiko.client.WarningPolicy'>}
[I 200414 10:48:10 settings:125] WarningPolicy
[I 200414 10:48:10 main:39] Listening on :8888 (http)
[D 200414 10:48:23 handler:224] netloc: localhost:8888
[D 200414 10:48:23 handler:227] host: localhost:8888
[D 200414 10:48:23 handler:410] ('arden-pv-003-drop8', 22, '***', '***', None)
[I 200414 10:48:23 handler:447] Connecting to arden-pv-003-drop8:22
[D 200414 10:48:23 transport:1819] starting thread (client mode): 0xb8a53388
[D 200414 10:48:23 transport:1819] Local version/idstring: SSH-2.0-paramiko_2.7.1
[D 200414 10:48:23 transport:1819] Remote version/idstring: SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
[I 200414 10:48:23 transport:1819] Connected (version 2.0, client OpenSSH_7.6p1)
[D 200414 10:48:23 transport:1819] kex algos:['curve25519-sha256', 'curve25519-sha256@libssh.org', 'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group16-sha512', 'diffie-hellman-group18-sha512', 'diffie-hellman-group14-sha256', 'diffie-hellman-group14-sha1'] server key:['ssh-rsa', 'rsa-sha2-512', 'rsa-sha2-256', 'ecdsa-sha2-nistp256', 'ssh-ed25519'] client encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] server encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] client mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] server mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
[D 200414 10:48:23 transport:1819] Kex agreed: curve25519-sha256@libssh.org
[D 200414 10:48:23 transport:1819] HostKey agreed: ssh-ed25519
[D 200414 10:48:23 transport:1819] Cipher agreed: aes128-ctr
[D 200414 10:48:23 transport:1819] MAC agreed: hmac-sha2-256
[D 200414 10:48:23 transport:1819] Compression agreed: none
[D 200414 10:48:23 transport:1819] kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
[D 200414 10:48:23 transport:1819] Switch to new keys ...
C:\Users\bo1li102\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\client.py:837: UserWarning: Unknown ssh-ed25519 host key for arden-pv-003-drop8: b'ce79b1c7b3ff0e1eda29a5aaf87e0658'
  key.get_name(), hostname, hexlify(key.get_fingerprint())
[I 200414 10:48:23 handler:87] Trying password authentication
[D 200414 10:48:23 transport:1819] userauth is OK
[I 200414 10:48:23 transport:1819] Authentication (password) successful!
[D 200414 10:48:23 channel:1212] [chan 0] Max packet in: 32768 bytes
[D 200414 10:48:23 transport:1819] Received global request "hostkeys-00@openssh.com"
[D 200414 10:48:23 transport:1819] Rejecting "hostkeys-00@openssh.com" global request from server.
[D 200414 10:48:23 channel:1212] [chan 0] Max packet out: 32768 bytes
[D 200414 10:48:23 transport:1819] Secsh channel 0 opened.
[D 200414 10:48:23 channel:1212] [chan 0] Sesch channel 0 request ok
[D 200414 10:48:23 channel:1212] [chan 0] Sesch channel 0 request ok
[D 200414 10:48:23 channel:1212] [chan 1] Max packet in: 32768 bytes
[D 200414 10:48:23 channel:1212] [chan 1] Max packet out: 32768 bytes
[D 200414 10:48:23 transport:1819] Secsh channel 1 opened.
[D 200414 10:48:23 channel:1212] [chan 1] Sesch channel 1 request ok
[D 200414 10:48:23 channel:1212] [chan 1] Sesch channel 1 request ok
[D 200414 10:48:23 channel:1212] [chan 1] EOF sent (1)
[D 200414 10:48:24 channel:1212] [chan 0] EOF received (0)
[D 200414 10:48:24 channel:1212] [chan 0] Unhandled channel request "exit-signal"
[D 200414 10:48:24 channel:1212] [chan 0] EOF sent (0)
[D 200414 10:48:24 channel:1212] [chan 1] EOF received (1)
[D 200414 10:48:24 handler:436] '$SHELL -ilc "locale charmap"' => b"Your machine *** is not in ip_map, please follow***'s mail to update the ip_map and hostname_map and try again\r\n"
[D 200414 10:48:24 channel:1212] [chan 1] Unhandled channel request "exit-signal"
[D 200414 10:48:24 channel:1212] [chan 2] Max packet in: 32768 bytes
[D 200414 10:48:24 channel:1212] [chan 2] Max packet out: 32768 bytes
[D 200414 10:48:24 transport:1819] Secsh channel 2 opened.
[D 200414 10:48:24 channel:1212] [chan 2] Sesch channel 2 request ok
[D 200414 10:48:24 channel:1212] [chan 2] Sesch channel 2 request ok
[D 200414 10:48:24 channel:1212] [chan 2] EOF sent (2)
[D 200414 10:48:24 channel:1212] [chan 2] EOF received (2)
[D 200414 10:48:24 handler:436] '$SHELL -ic "locale charmap"' => b'UTF-8\r\n'
[I 200414 10:48:24 web:2250] 200 POST / (::1) 1551.19ms
[D 200414 10:48:24 handler:224] netloc: localhost:8888
[D 200414 10:48:24 handler:227] host: localhost:8888
[I 200414 10:48:24 web:2250] 101 GET /ws?id=2223595926664 (::1) 22.01ms
[I 200414 10:48:24 handler:533] Connected from ::1:59149
[D 200414 10:48:24 worker:65] worker 2223595926664 on read
[D 200414 10:48:24 worker:73] b"Welcome to Ubuntu 18.04.2 LTS (GNU/Linux 4.15.18-arden-drop8-nvme+ x86_64)\r\n\r\n * Documentation:  https://help.ubuntu.com\r\n * Management:     https://landscape.canonical.com\r\n * Support:        https://ubuntu.com/advantage\r\n\r\n  System information as of Tue Apr 14 02:48:23 UTC 2020\r\n\r\n  System load:  1.0                Processes:           216\r\n  Usage of /:   6.6% of 467.31GB   Users logged in:     1\r\n  Memory usage: 9%                 IP address for eth0: ***\r\n  Swap usage:   0%\r\n\r\n * Kubernetes 1.18 GA is now available! See https://microk8s.io for docs or\r\n   install it with:\r\n\r\n     sudo snap install microk8s --channel=1.18 --classic\r\n\r\n * Multipass 1.1 adds proxy support for developers behind enterprise\r\n   firewalls. Rapid prototyping for cloud operations just got easier.\r\n\r\n     https://multipass.run/\r\n\r\n * Canonical Livepatch is available for installation.\r\n   - Reduce system reboots and improve kernel security. Activate at:\r\n     https://ubuntu.com/livepatch\r\n\r\n242 packages can be updated.\r\n138 updates are security updates.\r\n\r\n\r\nLast login: Tue Apr 14 02:47:40 2020 from ***\r\r\nYour machine *** is not in ip_map, please follow ***'s mail to update the ip_map and hostname_map and try again\r\n" from arden-pv-003-drop8:22
[D 200414 10:48:24 worker:78] b"Welcome to Ubuntu 18.04.2 LTS (GNU/Linux 4.15.18-arden-drop8-nvme+ x86_64)\r\n\r\n * Documentation:  https://help.ubuntu.com\r\n * Management:     https://landscape.canonical.com\r\n * Support:        https://ubuntu.com/advantage\r\n\r\n  System information as of Tue Apr 14 02:48:23 UTC 2020\r\n\r\n  System load:  1.0                Processes:           216\r\n  Usage of /:   6.6% of 467.31GB   Users logged in:     1\r\n  Memory usage: 9%                 IP address for eth0: 10.67.17.9\r\n  Swap usage:   0%\r\n\r\n * Kubernetes 1.18 GA is now available! See https://microk8s.io for docs or\r\n   install it with:\r\n\r\n     sudo snap install microk8s --channel=1.18 --classic\r\n\r\n * Multipass 1.1 adds proxy support for developers behind enterprise\r\n   firewalls. Rapid prototyping for cloud operations just got easier.\r\n\r\n     https://multipass.run/\r\n\r\n * Canonical Livepatch is available for installation.\r\n   - Reduce system reboots and improve kernel security. Activate at:\r\n     https://ubuntu.com/livepatch\r\n\r\n242 packages can be updated.\r\n138 updates are security updates.\r\n\r\n\r\nLast login: Tue Apr 14 02:47:40 2020 from ***\r\r\nYour machine *** is not in ip_map, please follow ***'s mail to update the ip_map and hostname_map and try again\r\n" to ::1:59149
[D 200414 10:48:24 worker:65] worker 2223595926664 on read
[D 200414 10:48:24 worker:73] b'' from arden-pv-003-drop8:22
[I 200414 10:48:24 worker:115] Closing worker 2223595926664 with reason: chan closed
[D 200414 10:48:24 transport:1819] EOF in transport thread
[I 200414 10:48:24 worker:122] Connection to arden-pv-003-drop8:22 lost
[D 200414 10:48:24 worker:125] {}
[D 200414 10:48:24 handler:556] '{"resize":[146,33]}' from ::1:59149
[I 200414 10:48:24 handler:579] Disconnected from ::1:59149

does that mean i need to update the ip_map or other reasons?
