### ISSUE TITLE
ValueError: Font file not found

### ISSUE THREAD

**Issue by wolf-joe** [huashengdun/webssh#149]
```shell
➜  ~ pwd
/home/pi
➜  ~ ls webssh/static/css/fonts/sarasa-mono-sc-regular.ttf 
webssh/static/css/fonts/sarasa-mono-sc-regular.ttf
➜  ~ wssh --font=sarasa-mono-sc-regular.ttf
[I 200410 13:25:03 settings:125] WarningPolicy
Traceback (most recent call last):
  File "/home/pi/.local/bin/wssh", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/webssh/main.py", line 47, in main
    app = make_app(make_handlers(loop, options), get_app_settings(options))
  File "/home/pi/.local/lib/python3.7/site-packages/webssh/settings.py", line 85, in get_app_settings
    os.path.join(base_dir, *font_dirs)),
  File "/home/pi/.local/lib/python3.7/site-packages/webssh/settings.py", line 188, in get_font_filename
    'Font file {!r} not found'.format(os.path.join(font_dir, font))
ValueError: Font file '/home/pi/.local/lib/python3.7/site-packages/webssh/static/css/fonts/sarasa-mono-sc-regular.ttf' not found
```

**Comment by huashengdun** [comment]
```bash
mv /home/pi/webssh/static/css/fonts/sarasa-mono-sc-regular.ttf  /home/pi/.local/lib/python3.7/site-packages/webssh/static/css/fonts/
```

**Comment by wolf-joe** [comment]
use current work dir as `base_dir` is better idea, i guess

**Comment by huashengdun** [comment]
The `base_dir` is the path of webssh where it is installed.
Also you don't have to specify the font option explicitly if you have only one font file in the fonts directory.

**Comment by huashengdun** [comment]
If you run command `python run.py`, then you don't have to move the font file.
