### ISSUE TITLE
Does Not Launch on Windows

### ISSUE THREAD

**Issue by elliot-labs** [huashengdun/webssh#184]
Hi Team,

I have attempted to launch this application on Windows and it does not launch.
```
C:\Windows\system32>wssh --address='127.0.0.1' --port=8888
[I 200928 09:47:49 settings:125] WarningPolicy
Traceback (most recent call last):
  File "C:\Python38\Scripts\wssh-script.py", line 33, in <module>
    sys.exit(load_entry_point('webssh==1.5.2', 'console_scripts', 'wssh')())
  File "c:\python38\lib\site-packages\webssh\main.py", line 50, in main
    app_listen(app, options.port, options.address, server_settings)
  File "c:\python38\lib\site-packages\webssh\main.py", line 32, in app_listen
    app.listen(port, address, **server_settings)
  File "c:\python38\lib\site-packages\tornado\web.py", line 2116, in listen
    server.listen(port, address)
  File "c:\python38\lib\site-packages\tornado\tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "c:\python38\lib\site-packages\tornado\netutil.py", line 117, in bind_sockets
    socket.getaddrinfo(address, port, family, socket.SOCK_STREAM, 0, flags),
  File "c:\python38\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed
```

This application launches and runs successfully in Windows Subsystem for Linux 2 on Ubuntu 20.04 LTS.
Just not native Windows 10.

Any help would be much appreciated.

Thanks!

**Comment by huashengdun** [comment]
Oops, seems Python command line in windows does not support single quotes.
So use double quotes instead.

**Comment by huashengdun** [comment]
Seems Python command line on windows does not support single quotes for strings.

**Comment by elliot-labs** [comment]
will do, one sec

**Comment by elliot-labs** [comment]
Just tried the wssh command by itself:
```
PS C:\Windows\system32> wssh
[I 201002 13:03:57 settings:125] WarningPolicy
Traceback (most recent call last):
  File "C:\Python38\Scripts\wssh-script.py", line 33, in <module>
    sys.exit(load_entry_point('webssh==1.5.2', 'console_scripts', 'wssh')())
  File "c:\python38\lib\site-packages\webssh\main.py", line 50, in main
    app_listen(app, options.port, options.address, server_settings)
  File "c:\python38\lib\site-packages\webssh\main.py", line 32, in app_listen
    app.listen(port, address, **server_settings)
  File "c:\python38\lib\site-packages\tornado\web.py", line 2116, in listen
    server.listen(port, address)
  File "c:\python38\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "c:\python38\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "c:\python38\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "c:\python38\lib\site-packages\tornado\platform\asyncio.py", line 100, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "c:\python38\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
```

**Comment by huashengdun** [comment]
The latest version https://github.com/huashengdun/webssh/releases/tag/v1.5.3 has fixed this error.

**Comment by elliot-labs** [comment]
Wonderful, it works!!!
thank you so much :)
