### ISSUE TITLE
Unable to start webserver  

### ISSUE THREAD

**Issue by divyanshumehta** [huashengdun/webssh#20]
First of all thanks, this app looks really cool, I am so excited to test it out. When i run the command `wssh myhomeserver` i get this error. Here is the stack-trace.
```Traceback (most recent call last):
  File "/usr/local/bin/wssh", line 101, in <module>
    client.invoke_shell(endpoint)
  File "/usr/local/lib/python2.7/dist-packages/wssh/client.py", line 45, in invoke_shell
    ssh = websocket.create_connection(endpoint)
AttributeError: 'module' object has no attribute 'create_connection'

```

**Comment by huashengdun** [comment]
Hi divyanshumehta,
Seems you have installed wrong application.
`/usr/local/lib/python2.7/dist-packages/wssh/client.py`  
The above line tells that you have installed an app called "wssh", not "webssh".
Although my app, the main entry point is also called "wssh".
I know this sounds a little confusing :).

**Comment by huashengdun** [comment]
Hi divyanshumehta,

**To install this app:** 
```pip install webssh```

**To run it:**
```wssh```

Maybe I need to update README for the instructions part.

**Comment by divyanshumehta** [comment]
Yup.. i mistyped the command after reading from the README
