### ISSUE TITLE
连接路由器报的超时，是什么堵塞了吗？

### ISSUE THREAD

**Issue by zjie-zheng** [huashengdun/webssh#207]
Traceback (most recent call last):
      File "/usr/local/lib64/python3.6/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/usr/local/lib64/python3.6/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/usr/local/lib/python3.6/site-packages/webssh/handler.py", line 509, in post
        worker = yield future
      File "/usr/local/lib64/python3.6/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 425, in result
        return self.__get_result()
      File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
        raise self._exception
      File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/local/lib/python3.6/site-packages/webssh/handler.py", line 465, in ssh_connect
        self.get_default_encoding(ssh)
      File "/usr/local/lib/python3.6/site-packages/webssh/handler.py", line 431, in get_default_encoding
        _, stdout, _ = ssh.exec_command(command, get_pty=True)
      File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 508, in exec_command
        chan = self._transport.open_session(timeout=timeout)
      File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 879, in open_session
        timeout=timeout,
      File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 1006, in open_channel
        raise e
      File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 2055, in run
        ptype, m = self.packetizer.read_message()
      File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 459, in read_message
        header = self.read_all(self.__block_size_in, check_rekey=True)
      File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 303, in read_all
        raise EOFError()
    EOFError

**Comment by zjie-zheng** [comment]
已解决，把delay 提高点。
