### ISSUE TITLE
EOFError when Using MFA (One-time Password)

### ISSUE THREAD

**Issue by hzxie** [huashengdun/webssh#225]
```
    HTTPServerRequest(protocol='http', host='localhost:6080', method='POST', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/usr/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/usr/lib/python3.9/site-packages/webssh/handler.py", line 509, in post
        worker = yield future
      File "/usr/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/usr/lib/python3.9/concurrent/futures/_base.py", line 438, in result
        return self.__get_result()
      File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
        raise self._exception
      File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/lib/python3.9/site-packages/webssh/handler.py", line 461, in ssh_connect
        chan = ssh.invoke_shell(term=term)
      File "/usr/lib/python3.9/site-packages/paramiko/client.py", line 545, in invoke_shell
        chan = self._transport.open_session()
      File "/usr/lib/python3.9/site-packages/paramiko/transport.py", line 875, in open_session
        return self.open_channel(
      File "/usr/lib/python3.9/site-packages/paramiko/transport.py", line 1006, in open_channel
        raise e
      File "/usr/lib/python3.9/site-packages/paramiko/transport.py", line 2055, in run
        ptype, m = self.packetizer.read_message()
      File "/usr/lib/python3.9/site-packages/paramiko/packet.py", line 459, in read_message
        header = self.read_all(self.__block_size_in, check_rekey=True)
      File "/usr/lib/python3.9/site-packages/paramiko/packet.py", line 303, in read_all
        raise EOFError()
    EOFError
```

**Comment by huashengdun** [comment]
Try starting webssh like `wssh --encoding='utf-8'`.

**Comment by hzxie** [comment]
It works well with `google-authentication` in ubuntu. However, it cannot work well with [jumpserver](https://github.com/jumpserver/jumpserver).
It seems that the handler is not invoked by the jumpserver.
