### ISSUE TITLE
WebSSH not liking my key/certificate

### ISSUE THREAD

**Issue by stefan-reich** [huashengdun/webssh#243]
Command:

```
wssh --port=8080 --sslport=4433 --certfile='/etc/letsencrypt/live/gazelle.rocks/privkey.pem' \
  --keyfile='/etc/letsencrypt/live/gazelle.rocks/cert.pem' --xheaders=False --policy=reject
```

Output:

```
I 211003 17:31:27 settings:125] RejectPolicy
Traceback (most recent call last):
  File "/usr/local/bin/wssh", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/webssh/main.py", line 48, in main
    ssl_ctx = get_ssl_context(options)
  File "/usr/local/lib/python3.6/dist-packages/webssh/settings.py", line 143, in get_ssl_context
    ssl_ctx.load_cert_chain(options.certfile, options.keyfile)
ssl.SSLError: [SSL] PEM lib (_ssl.c:3503)
```

I also tried with fullchain.pem instead of cert.pem, but no difference. What's wrong?

**Comment by huashengdun** [comment]
Is it a certificate format problem?
I used this script https://github.com/diafygi/acme-tiny to generate the key/certificate files and they worked.
