### ISSUE TITLE
No existing session

### ISSUE THREAD

**Issue by moox2020** [huashengdun/webssh#251]
connect的时候报错：No existing session

[I 211106 16:59:35 handler:161] Parsing private key 'id_rsa'
[I 211106 16:59:35 handler:448] Connecting to 106.15.45.129:8888
[E 211106 16:59:38 handler:512] Traceback (most recent call last):
      File "/root/webssh/tutorial-env/lib64/python3.6/site-packages/webssh/handler.py", line 510, in post
        worker = yield future
      File "/root/webssh/tutorial-env/lib64/python3.6/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 425, in result
        return self.__get_result()
      File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
        raise self._exception
      File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/root/webssh/tutorial-env/lib64/python3.6/site-packages/webssh/handler.py", line 451, in ssh_connect
        ssh.connect(*args, timeout=options.timeout)
      File "/root/webssh/tutorial-env/lib64/python3.6/site-packages/paramiko/client.py", line 412, in connect
        server_key = t.get_remote_server_key()
      File "/root/webssh/tutorial-env/lib64/python3.6/site-packages/paramiko/transport.py", line 834, in get_remote_server_key
        raise SSHException("No existing session")
    paramiko.ssh_exception.SSHException: No existing session
    
[I 211106 16:59:38 web:2243] 200 POST / (219.228.146.58) 3027.09ms

![image](https://user-images.githubusercontent.com/11605714/140604060-70c69d95-fc0d-4a27-962a-8c96780b7b59.png)

**Comment by huashengdun** [comment]
试试把delay设置大点, `wssh --delay=6`

**Comment by moox2020** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，您的邮件我已收到，我会尽快给您回复。
