### ISSUE TITLE
Failed to ssh a Ruijie Device, error is listed in the comments

### ISSUE THREAD

**Issue by crusaderay** [huashengdun/webssh#314]
[E 221207 12:05:07 web:1798] Uncaught exception POST / (x.x.x.x)
    HTTPServerRequest(protocol='http', host='x.x.x.x:8888', method='POST', uri='/', version='HTTP/1.1', remote_ip='x.x.x.x')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 776, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/usr/local/lib/python3.10/dist-packages/webssh/handler.py", line 514, in post
        worker = yield future
      File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 769, in run
        value = future.result()
      File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
        return self.__get_result()
      File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
        raise self._exception
      File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/local/lib/python3.10/dist-packages/webssh/handler.py", line 470, in ssh_connect
        self.get_default_encoding(ssh)
      File "/usr/local/lib/python3.10/dist-packages/webssh/handler.py", line 430, in get_default_encoding
        _, stdout, _ = ssh.exec_command(command,
      File "/usr/lib/python3/dist-packages/paramiko/client.py", line 510, in exec_command
        chan = self._transport.open_session(timeout=timeout)
      File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 919, in open_session
        return self.open_channel(
      File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 1050, in open_channel
        raise e
      File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 2109, in run
        ptype, m = self.packetizer.read_message()
      File "/usr/lib/python3/dist-packages/paramiko/packet.py", line 459, in read_message
        header = self.read_all(self.__block_size_in, check_rekey=True)
      File "/usr/lib/python3/dist-packages/paramiko/packet.py", line 303, in read_all
        raise EOFError()
    EOFError

This happens only for Ruijie device. All other juniper or cisco, huawei etc works fine. Seems like the socket is not getting anything from the server side.

**Comment by huashengdun** [comment]
Try this command `wssh -encoding="utf-8"` to start your webssh server.

**Comment by crusaderay** [comment]
Thank you, you are awesome!.
