### ISSUE TITLE
local no issues but with proxy pass from nginx 404 

### ISSUE THREAD

**Issue by imstupidwithlinux** [huashengdun/webssh#343]
this is what the website shows when its in debug mode 

```
Traceback (most recent call last):
  File "/home/frgd/.local/lib/python3.9/site-packages/tornado/web.py", line 1690, in _execute
    result = self.prepare()
  File "/home/frgd/.local/lib/python3.9/site-packages/webssh/handler.py", line 312, in prepare
    raise tornado.web.HTTPError(404)
tornado.web.HTTPError: HTTP 404: Not Found
```

my nginx config
```
                location  /Konsole {
                        proxy_pass http://localhost:7243/;
                        proxy_http_version 1.1;
                        proxy_read_timeout 300;
                        proxy_set_header Upgrade $http_upgrade;
                        proxy_set_header Connection "upgrade";
                        proxy_set_header Host $http_host;
                        proxy_set_header X-Real-IP $remote_addr;
                        proxy_set_header X-Real-PORT $remote_port;
                }
```

**Comment by huashengdun** [comment]
Seems the route is not correct. 
Have you tried removing the trailing slash in this line `proxy_pass http://localhost:7243/;`?

**Comment by imstupidwithlinux** [comment]
i figured it out now i had to do it like this 

```
                location  /Konsole/ {
                        proxy_pass http://localhost:7243/;
                        proxy_http_version 1.1;
                        proxy_read_timeout 300;
                        proxy_set_header Upgrade $http_upgrade;
                        proxy_set_header Connection "upgrade";
                        proxy_set_header Host $http_host;
                        proxy_set_header X-Real-IP $remote_addr;
                        proxy_set_header X-Real-PORT $remote_port;
                }
```
