### ISSUE TITLE
报的tornado语法错误，tornado版本是6.0.2

### ISSUE THREAD

**Issue by Whitessky** [huashengdun/webssh#67]
Traceback (most recent call last):
  File "/bin/wssh", line 9, in <module>
    load_entry_point('webssh==1.2.0', 'console_scripts', 'wssh')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/webssh/main.py", line 2, in <module>
    import tornado.web
  File "/usr/lib64/python2.7/site-packages/tornado/web.py", line 205
    application: "Application",
               ^
SyntaxError: invalid syntax

**Comment by huashengdun** [comment]
使用的是什么版本的系统？
这个 https://github.com/huashengdun/webssh/issues/54 可能对你有帮助。

**Comment by Whitessky** [comment]
已经解决，错误原因是tornado最新版本不支持python2.7,换成低版本的就好。
